# Generated by Django 2.0.7 on 2019-06-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('data_type', models.CharField(choices=[(1, 'Video'), (2, 'Image')], max_length=30)),
                ('receive_time', models.DateTimeField()),
                ('size', models.CharField(max_length=30)),
                ('storage_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('is_login', models.BooleanField(default=False)),
                ('last_login_time', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('device_type', models.CharField(choices=[(1, 'Phone'), (2, 'Camera')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='from_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='storage.device'),
        ),
    ]
