# Generated by Django 2.0.7 on 2019-06-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20190619_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'Camera')], default=1),
        ),
    ]
