# Generated by Django 2.0.7 on 2019-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20190619_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='storage_location',
            field=models.CharField(max_length=100),
        ),
    ]
